### ISSUE TITLE
Website can't access

### ISSUE THREAD

**Issue by xiao-kong-long** [zhaofangyuan98/SDMBench#3]
Dear developer, I have found your provided website url [http://sdmbench.drai.cn/](http://sdmbench.drai.cn/) can not be accessible. May the webservice is down?

**Comment by zhaofangyuan98** [comment]
Hello! Thank you for your notification. It seems that there may be a misunderstanding, because I have checked and found that the website http://sdmbench.drai.cn/ can be accessed normally. Please try refreshing the page, clearing your browser cache or trying again in a different network environment. If the problem persists, please provide us with more details, such as the specific error message you are experiencing, so that we can further assist you in resolving the issue.
